name: CI

on:
    push:
        branches: ['main']
        tags: ['**']
    pull_request:
        # Build all pull requests, regardless of what their base branch is.
        branches: ['**']
        types:
            # Default types (see https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request)
            - opened
            - synchronize
            - reopened
            # Extra types (re-run CI when marking PR for "ready for review")
            - ready_for_review

env:
    node_version: 22

# Automatically cancel previous runs for the same ref (i.e. branch)
concurrency:
    group: ${{ github.ref }}-${{ github.event_name }}
    cancel-in-progress: true

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Check out the code
              uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.node_version }}
                  token: ${{ secrets.GH_DOTCOM_TOKEN }}
                  cache: 'npm'
                  cache-dependency-path: 'package-lock.json'
                  registry-url: 'https://registry.npmjs.com'
            - name: Install dependencies
              run: npm ci
            - name: Lint code (ESLint)
              run: npm run lint:eslint
            - name: Lint code (Prettier)
              run: npm run lint:prettier
            - name: Lint code (TypeScript)
              run: npm run lint:tsc

    test:
        runs-on: ubuntu-latest
        steps:
            - name: Check out the code
              uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.node_version }}
                  token: ${{ secrets.GH_DOTCOM_TOKEN }}
                  cache: 'npm'
                  cache-dependency-path: 'package-lock.json'
                  registry-url: 'https://registry.npmjs.com'
            - name: Install dependencies
              run: npm ci
            - name: Run Unit Tests
              run: nmp run test
